### ISSUE TITLE
Update testdata/* paths in some default graphics 

### ISSUE THREAD

**Issue by kwhitehall** [chrismattmann/tika-img-similarity#20]
@dongnizh  Currently the D3viz (dynamic-circlepacking.html, compositeViz.html, dynamic-cluster.html don't show anything because the paths to the json files are incorrect.

**Comment by dongnizh** [comment]
Hi @kwhitehall  The way I am thinking to use this program is to compare similarity of images located in your local folders. If you run a series of python command, it will generate new files with fixed names. However, testdata folder is just used for test only I believe.
