### ISSUE TITLE
metadata value is a list

### ISSUE THREAD

**Issue by dongnizh** [chrismattmann/tika-img-similarity#23]
Hi @chrismattmann the new version of tika-python returned metadata value as a list :

![0a812442-4e79-41d7-a05a-1b10e12c0809](https://cloud.githubusercontent.com/assets/6832510/7479926/ca0bc31e-f319-11e4-952e-bba034c8ba8d.png)

This will influence value-similarity.py, cuz it was string in the former version of tika-python. Do I need to update it to be applicable for the new version of tika-python? Is this what you intend to do ?

**Comment by chrismattmann** [comment]
Yes please update we want to use the new version of Tika-Python

**Comment by chrismattmann** [comment]
@dongnizh

**Comment by dongnizh** [comment]
@chrismattmann will do!!!

**Comment by chrismattmann** [comment]
Thanks @dongnizh !

**Comment by dongnizh** [comment]
This is done in #24 .Will update in ETLlib.
