### ISSUE TITLE
update -c for several file comparing

### ISSUE THREAD

**Issue by dongnizh** [chrismattmann/tika-img-similarity#25]
@chrismattmann Currently, similarity with -c flag can only compare two files. I am thinking to make it working for comparing several files. Such as:
```
-c file1 file2 file3 .......
```
The length of files depends on the users operations.
Any thoughts?

**Comment by chrismattmann** [comment]
great idea. However doesn't -c compute containment rather than resemblance? Containment is a pair-wise operation, right @dongnizh ?

**Comment by dongnizh** [comment]
@chrismattmann Yes. -c works for containment (pairwise comparison) right now.

**Comment by chrismattmann** [comment]
So how can we make it work for a whole bunch of files @dongnizh

**Comment by dongnizh** [comment]
@chrismattmann I do not know. I was thinking to discard this idea if it is not that useful. What is your idea?

**Comment by chrismattmann** [comment]
well one idea that would probably would work would be:

1. if -c includes only two files, compute containment.
2. if -c includes > two files, compute resemblance, but only of those provided files
3. if -c includes < two files, print Usage, throw error. Thoughts?

@dongnizh

**Comment by dongnizh** [comment]
@chrismattmann  Great. Update soon.

**Comment by chrismattmann** [comment]
+1 thanks @dongnizh

**Comment by dongnizh** [comment]
This is closed #30

**Comment by chrismattmann** [comment]
#30 closes #25
