### ISSUE TITLE
Write a better manual and README

### ISSUE THREAD

**Issue by chrismattmann** [chrismattmann/tika-img-similarity#26]
The README has grown really out of date, and I think we could write a way better one with pictures and info on how to generate them. @dongnizh do you want to take a crack at this? I can help.

**Comment by dongnizh** [comment]
@chrismattmann So how to start it? Any instructions?

**Comment by chrismattmann** [comment]
yep the idea would be to update the README to include:

1. How to check out the project
2. How to run it on a directory of images
 a. What commands to run
3. What HTML files to edit and how they should be edited or copied to a folder that is browseable by the web, etc.

@dongnizh

**Comment by dongnizh** [comment]
Got it! Will start it tomorrow. Thanks for suggestions. @chrismattmann

**Comment by dongnizh** [comment]
This is closed #27
